### recuperar todas las peliculas
GET http://localhost:3000/movies

### recuperar pelicula por id
GET http://localhost:3000/movies/1

### recuperar pelicula por genero
GET http://localhost:3000/movies?genre=fantasy

### crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json


{
  "title": "The Godfather",
  "year": 1972,
  "genre": ["Crime", "Drama"],
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg"
}

### actualizar una pelicula
PATCH http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

{
  "year": 1975
}

### eliminar una pelicula
DELETE http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json
